# Generated by Django 4.1 on 2022-11-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('emp_no', models.IntegerField()),
                ('age', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
